anchor_version = "0.17.0"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/mint-keypair.json"

[programs.devnet]
draffle = "RAfqHaNYVVNoc5Xj5fgpZD9QRXothdxQ2frNsDCvc5J"

[programs.mainnet]
draffle = "RAfqHaNYVVNoc5Xj5fgpZD9QRXothdxQ2frNsDCvc5J"

[scripts]
test = "mocha -t 1000000 tests"